# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  IMAGE_NAME: ${{ secrets.DOCKER_GCP_LOCATION }}/case-processor
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: adopt
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Run fmt
      run: mvn fmt:check
    - name: docker login
      run: |
        echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin ${{ secrets.DOCKER_REGISTRY }}
    - name: Run tests
      run: mvn verify jacoco:report
    - name: Run Docker images
      run: docker images
    - name: Docker tag image
      if: github.ref == 'refs/heads/master'
      run: docker tag ${{ secrets.GCR_LOCATION }} ${{ env.IMAGE_NAME }}:new_image
    - name: Docker push image
      if: github.ref == 'refs/heads/master'
      run: docker push ${{ env.IMAGE_NAME }}:new_image 
